# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20160503_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='is_favorite',
            field=models.BooleanField(default=True),
        ),
    ]
